app: test-app
env: production
namespace: default
chart:
  repository: https://chart.onechart.dev
  name: onechart
  version: 0.36.0
values:
  gitRepository: gimlet-io/test-app
  gitSha: '{{ .GITHUB_SHA }}'
strategicMergePatches: ""
json6902Patches: []
manifests: ""
