app: demo-app
env: prod
namespace: default
deploy:
  branch: main
  event: push
chart:
  repository: https://chart.onechart.dev
  name: onechart
  version: 0.38.0
values:
  image:
    repository: "ghcr.io/wonderschool/demo-app"
    tag: "{{ .GITHUB_SHA }}"
  imagePullSecrets:
    - name: dockerconfigjson-github-com
  containerPort: 9000
  ingresses:
    - host: demo-app.wonderschool.com
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
      tlsEnabled: true
strategicMergePatches: ""
json6902Patches: []
manifests: ""
